In [41]:
#%pip install numpy
#%pip install pandas
#%pip install matplotlib
#%pip install scikit-learn

## Import Libraries

In [42]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Import Data

In [43]:
# import dataset
dataset = pd.read_csv('Data.csv')

In [ ]:
dataset.head()

## Select X Data

In [44]:
# [rows,columns]
# [:,:-1] - all rows + all columns except the last column
X = dataset.iloc[:,:-1].values
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Select y Data

In [45]:
# all rows and only the last column
y = dataset.iloc[:,-1].values
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Fix Missing Data

In [46]:
# fix missing data
# replace missing values with the average of existing values

from sklearn.impute import SimpleImputer

# create imputer object
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# fit imputer
# note, upper bound is excluded (1:2 -> 1:3 to get the second 2 columns)
imputer.fit(X[:,1:3])

# apply imputer
X[:,1:3] = imputer.transform(X[:,1:3])



In [47]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encode Categorical Data (One-Hot Encoding)

In [48]:
# encoding categorical data

from sklearn.compose import ColumnTransformer

# one-hot encoding: create a column for each category
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [49]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


## Transform Boolean Labels

In [50]:
# transform Yes/No to 1/0

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [51]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Split Data (training, test)

In [52]:
# split data: training and test 

from sklearn.model_selection import train_test_split

# random_state = 1; get the same train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [53]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [54]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [55]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [56]:
print(y_test)

[0 1]


## Scale X Data

In [58]:
# feature scaling
# scales data so ensure no one attribute over influences the data
# data should be scaled after the data has been split
#   the test set should be considered a new set
#   the mean and standard deviation should be calcualted separately for both sets

# standardization = (x - mean(x))/standard_deviation(x); {-3,3}; will work all the time
# normalization = (x - min(x))/(max(x) - min(x); {0,1}; will work when features have a normal distribution

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

# scaling is not applied to dummy variables because they are already between {-3,3}
#   would also lose the interpretation of the encoding

X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])



In [59]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [60]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
