In [41]:
#%pip install numpy
#%pip install pandas
#%pip install matplotlib
#%pip install scikit-learn

## Import Libraries

In [42]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Import Data

In [43]:
# import dataset
dataset = pd.read_csv('Data.csv')

In [ ]:
dataset.head()

## Select Data

In [44]:
# [rows,columns]
# [:,:-1] - all rows + all columns except the last column
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Split Data (training, test)

In [52]:
# split data: training and test 

from sklearn.model_selection import train_test_split

# random_state = 1; get the same train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [53]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
